// Copyright 2026 The spanner-manager Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codegen

import (
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestGenerator_Generate_BasicFiles(t *testing.T) {
	typ := Type{
		Name:  "Users",
		Table: "Users",
		Fields: []Field{
			{
				Name:            "UserID",
				ColumnName:      "user_id",
				GoType:          "int64",
				SpannerType:     "INT64",
				BaseSpannerType: "INT64",
				NotNull:         true,
				IsPrimaryKey:    true,
			},
			{
				Name:            "Name",
				ColumnName:      "name",
				GoType:          "string",
				SpannerType:     "STRING(MAX)",
				BaseSpannerType: "STRING",
				NotNull:         true,
			},
		},
	}
	refreshTypeMetadata(&typ)

	outDir := generateFromSchema(t, &Schema{Types: []Type{typ}}, Options{
		PackageName: "models",
		Suffix:      ".yo.go",
	})

	tests := map[string]struct {
		path     string
		contains []string
	}{
		"header": {
			path: filepath.Join(outDir, "spanner_header.yo.go"),
			contains: []string{
				"package models",
				"Code generated by spanner-manager",
				"var (\n\t_ = context.Background\n\t_ = fmt.Sprintf\n\t_ = spanner.Key{}\n\t_ = iterator.Done\n)",
			},
		},
		"helper": {
			path: filepath.Join(outDir, "spanner_db.yo.go"),
			contains: []string{
				"type SpannerDB interface",
				"var SpannerLog",
				"type JSONString[T any] struct",
			},
		},
		"type": {
			path: filepath.Join(outDir, "users.yo.go"),
			contains: []string{
				"type Users struct",
				"UserID int64",
				`spanner:"name"`,
				"func (t *Users) Insert() *spanner.Mutation",
				"func FindUsersByPrimaryKey(ctx context.Context, db SpannerDB, userID int64) (*Users, error)",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			content := readTextFile(t, tt.path)
			for _, want := range tt.contains {
				if !strings.Contains(content, want) {
					t.Fatalf("%s missing %q", tt.path, want)
				}
			}
		})
	}
}

func TestGenerator_Generate_IndexMetadataDoesNotExpandAPISurface(t *testing.T) {
	root := newCompileFixtureRoot(t)
	outDir := generateFromDDL(t, root, `CREATE TABLE Users (
		UserId INT64 NOT NULL,
		Email STRING(256),
		CreatedAt TIMESTAMP NOT NULL,
		DisplayName STRING(MAX),
	) PRIMARY KEY (UserId);
	CREATE INDEX UsersByCreatedAt ON Users(CreatedAt DESC) STORING (DisplayName);
	CREATE UNIQUE INDEX UsersByEmail ON Users(Email)`, Options{
		PackageName: "models",
	})

	if diff := cmp.Diff([]string{
		"spanner_db.spanner.go",
		"spanner_header.spanner.go",
		"users.spanner.go",
	}, listFiles(t, outDir)); diff != "" {
		t.Fatalf("generated files mismatch (-want +got):\n%s", diff)
	}

	helperContent := readTextFile(t, filepath.Join(outDir, "spanner_db.spanner.go"))
	for name, want := range map[string]string{
		"read row": "ReadRow(",
		"query":    "Query(",
	} {
		if !strings.Contains(helperContent, want) {
			t.Fatalf("spanner_db.spanner.go missing %s method %q", name, want)
		}
	}
	for name, unwanted := range map[string]string{
		"read using index": "ReadUsingIndex(",
		"query by index":   "QueryByIndex(",
	} {
		if strings.Contains(helperContent, unwanted) {
			t.Fatalf("spanner_db.spanner.go unexpectedly contains %s method %q", name, unwanted)
		}
	}

	typeContent := readTextFile(t, filepath.Join(outDir, "users.spanner.go"))
	for name, want := range map[string]string{
		"primary key finder": "func FindUsersByPrimaryKey(ctx context.Context, db SpannerDB, userID int64) (*Users, error)",
		"insert mutation":    "func (t *Users) Insert() *spanner.Mutation",
	} {
		if !strings.Contains(typeContent, want) {
			t.Fatalf("users.spanner.go missing %s %q", name, want)
		}
	}
	for name, unwanted := range map[string]string{
		"secondary index finder": "FindUsersByCreatedAt",
		"unique index finder":    "FindUsersByEmail",
		"query builder":          "QueryUsersBy",
	} {
		if strings.Contains(typeContent, unwanted) {
			t.Fatalf("users.spanner.go unexpectedly contains %s %q", name, unwanted)
		}
	}

	runGoTestDir(t, outDir)
}

func TestGenerator_Generate_TableSelection(t *testing.T) {
	tests := map[string]struct {
		opts      Options
		wantFiles []string
		wantErr   string
	}{
		"success: ignore tables": {
			opts: Options{
				PackageName:  "models",
				IgnoreTables: []string{"Secrets"},
			},
			wantFiles: []string{
				"spanner_db.spanner.go",
				"spanner_header.spanner.go",
				"users.spanner.go",
			},
		},
		"success: include tables": {
			opts: Options{
				PackageName:   "models",
				IncludeTables: []string{"Secrets"},
			},
			wantFiles: []string{
				"secrets.spanner.go",
				"spanner_db.spanner.go",
				"spanner_header.spanner.go",
			},
		},
		"error: unknown included table": {
			opts: Options{
				PackageName:   "models",
				IncludeTables: []string{"Missing"},
			},
			wantErr: `unknown table "Missing"`,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			outDir := filepath.Join(t.TempDir(), "models")
			tt.opts.OutDir = outDir
			err := NewGenerator(tt.opts).Generate(newSimpleSchema("Users", "Secrets"))
			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("Generate() error = nil, want %q", tt.wantErr)
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("Generate() error = %v, want substring %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("Generate() error = %v", err)
			}

			if diff := cmp.Diff(tt.wantFiles, listFiles(t, outDir)); diff != "" {
				t.Fatalf("generated files mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestGenerator_Generate_NamingOptions(t *testing.T) {
	tests := map[string]struct {
		schema          *Schema
		opts            Options
		wantFiles       []string
		wantTypeSnippet string
	}{
		"success: singularize with suffix": {
			schema: newSimpleSchema("FactoryControls"),
			opts: Options{
				PackageName:     "models",
				SingularizeRows: true,
				RowSuffix:       "Row",
			},
			wantFiles: []string{
				"factorycontrolrow.spanner.go",
				"spanner_db.spanner.go",
				"spanner_header.spanner.go",
			},
			wantTypeSnippet: "type FactoryControlRow struct",
		},
		"success: row name override": {
			schema: newSimpleSchema("FleetPools"),
			opts: Options{
				PackageName: "models",
				Config: &Config{
					Tables: []TableConfig{
						{Name: "FleetPools", RowName: "FleetPoolRow"},
					},
				},
			},
			wantFiles: []string{
				"fleetpoolrow.spanner.go",
				"spanner_db.spanner.go",
				"spanner_header.spanner.go",
			},
			wantTypeSnippet: "type FleetPoolRow struct",
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			outDir := filepath.Join(t.TempDir(), "models")
			tt.opts.OutDir = outDir

			if err := NewGenerator(tt.opts).Generate(tt.schema); err != nil {
				t.Fatalf("Generate() error = %v", err)
			}

			if diff := cmp.Diff(tt.wantFiles, listFiles(t, outDir)); diff != "" {
				t.Fatalf("generated files mismatch (-want +got):\n%s", diff)
			}

			typeFiles := filterFiles(tt.wantFiles, func(name string) bool {
				return strings.HasSuffix(name, ".spanner.go") && !strings.HasPrefix(name, "spanner_")
			})
			if len(typeFiles) != 1 {
				t.Fatalf("expected exactly one type file, got %v", typeFiles)
			}
			content := readTextFile(t, filepath.Join(outDir, typeFiles[0]))
			if !strings.Contains(content, tt.wantTypeSnippet) {
				t.Fatalf("%s missing %q", typeFiles[0], tt.wantTypeSnippet)
			}
		})
	}
}

func TestGenerator_Generate_CustomTypeImports(t *testing.T) {
	ddl := `CREATE TABLE Users (
		id INT64 NOT NULL,
		data JSON,
	) PRIMARY KEY (id)`

	root := newCompileFixtureRoot(t)
	outDir := generateFromDDL(t, root, ddl, Options{
		PackageName: "models",
		Config: &Config{
			Tables: []TableConfig{
				{
					Name: "Users",
					Columns: []ColumnConfig{
						{
							Name:       "data",
							CustomType: "json.RawMessage",
							Imports:    []string{"json=encoding/json"},
						},
					},
				},
			},
		},
	})

	content := readTextFile(t, filepath.Join(outDir, "users.spanner.go"))
	tests := map[string]string{
		"custom type":   `Data json.RawMessage`,
		"custom import": `json "encoding/json"`,
	}
	for name, want := range tests {
		t.Run(name, func(t *testing.T) {
			if !strings.Contains(content, want) {
				t.Fatalf("users.spanner.go missing %q", want)
			}
		})
	}

	if got, want := strings.Count(content, `"encoding/json"`), 1; got != want {
		t.Fatalf(`users.spanner.go imports "encoding/json" %d times, want %d`, got, want)
	}

	runGoTestDir(t, outDir)
}

func TestGenerator_Generate_CompositePrimaryKeyOrder(t *testing.T) {
	ddl := `CREATE TABLE Memberships (
		a INT64 NOT NULL,
		b STRING(MAX) NOT NULL,
	) PRIMARY KEY (b, a)`

	root := newCompileFixtureRoot(t)
	outDir := generateFromDDL(t, root, ddl, Options{PackageName: "models"})
	content := readTextFile(t, filepath.Join(outDir, "memberships.spanner.go"))

	tests := map[string]string{
		"primary key column order": `func MembershipsPrimaryKeys() []string {
	return []string{
		"b",
		"a",
	}
}`,
		"find signature order": `func FindMembershipsByPrimaryKey(ctx context.Context, db SpannerDB, b string, a int64) (*Memberships, error)`,
		"delete key order": `return spanner.Delete("Memberships", spanner.Key{
		t.B,
		t.A,
	})`,
	}
	for name, want := range tests {
		t.Run(name, func(t *testing.T) {
			if !strings.Contains(content, want) {
				t.Fatalf("memberships.spanner.go missing %q", want)
			}
		})
	}

	runGoTestDir(t, outDir)
}

func TestGenerator_Generate_CommitTimestampHelpers(t *testing.T) {
	ddl := `CREATE TABLE Runs (
		run_id INT64 NOT NULL,
		updated_at TIMESTAMP OPTIONS (allow_commit_timestamp=true),
	) PRIMARY KEY (run_id)`

	outDir := generateFromDDL(t, t.TempDir(), ddl, Options{PackageName: "models"})
	content := readTextFile(t, filepath.Join(outDir, "runs.spanner.go"))

	tests := map[string]string{
		"commit timestamp columns":             `func RunsCommitTimestampColumns() []string`,
		"set commit timestamps helper":         `func (t *Runs) SetCommitTimestamps(excludeColumns ...string)`,
		"insert or update helper":              `func (t *Runs) InsertOrUpdateWithCommitTimestamps(excludeColumns ...string) *spanner.Mutation`,
		"nullable commit timestamp expression": `spanner.NullTime{Time: spanner.CommitTimestamp, Valid: true}`,
	}
	for name, want := range tests {
		t.Run(name, func(t *testing.T) {
			if !strings.Contains(content, want) {
				t.Fatalf("runs.spanner.go missing %q", want)
			}
		})
	}
}

func TestGenerator_Generate_IndexMetadataDoesNotExpandAPI(t *testing.T) {
	ddl := `CREATE TABLE Users (
		user_id INT64 NOT NULL,
		email STRING(256),
		created_at TIMESTAMP NOT NULL,
		name STRING(MAX),
	) PRIMARY KEY (user_id);
	CREATE UNIQUE INDEX UsersByEmail ON Users(email);
	CREATE INDEX UsersByCreatedAt ON Users(created_at DESC) STORING (name)`

	root := newCompileFixtureRoot(t)
	outDir := generateFromDDL(t, root, ddl, Options{PackageName: "models"})

	if diff := cmp.Diff([]string{
		"spanner_db.spanner.go",
		"spanner_header.spanner.go",
		"users.spanner.go",
	}, listFiles(t, outDir)); diff != "" {
		t.Fatalf("generated files mismatch (-want +got):\n%s", diff)
	}

	tests := map[string]struct {
		path        string
		contains    []string
		notContains []string
	}{
		"shared db helper remains query-first": {
			path: filepath.Join(outDir, "spanner_db.spanner.go"),
			contains: []string{
				"ReadRow(ctx context.Context, table string, key spanner.Key, columns []string) (*spanner.Row, error)",
				"Query(ctx context.Context, statement spanner.Statement) *spanner.RowIterator",
			},
			notContains: []string{
				"ReadUsingIndex(",
			},
		},
		"type surface remains CRUD plus primary-key lookup": {
			path: filepath.Join(outDir, "users.spanner.go"),
			contains: []string{
				"func (t *Users) Insert() *spanner.Mutation",
				"func (t *Users) Update() *spanner.Mutation",
				"func (t *Users) InsertOrUpdate() *spanner.Mutation",
				"func (t *Users) Delete() *spanner.Mutation",
				"func FindUsersByPrimaryKey(ctx context.Context, db SpannerDB, userID int64) (*Users, error)",
			},
			notContains: []string{
				"FindUsersByEmail(",
				"FindUsersByCreatedAt(",
				"ListUsersByEmail(",
				"ListUsersByCreatedAt(",
				"QueryBuilder",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			content := readTextFile(t, tt.path)
			for _, want := range tt.contains {
				if !strings.Contains(content, want) {
					t.Fatalf("%s missing %q", tt.path, want)
				}
			}
			for _, unwanted := range tt.notContains {
				if strings.Contains(content, unwanted) {
					t.Fatalf("%s unexpectedly contains %q", tt.path, unwanted)
				}
			}
		})
	}

	runGoTestDir(t, outDir)
}

func TestGenerator_Generate_CompileGeneratedOutput(t *testing.T) {
	tests := map[string]struct {
		ddl       string
		configure func(t *testing.T, root string) Options
	}{
		"success: timestamp array and commit timestamp compile": {
			ddl: `CREATE TABLE Runs (
				id STRING(MAX) NOT NULL,
				repository_ids ARRAY<STRING(MAX)>,
				created_at TIMESTAMP NOT NULL,
				updated_at TIMESTAMP OPTIONS (allow_commit_timestamp=true),
			) PRIMARY KEY (id)`,
		},
		"success: typed json string wrapper compiles": {
			ddl: `CREATE TABLE Runs (
				id STRING(MAX) NOT NULL,
				metadata STRING(MAX),
			) PRIMARY KEY (id)`,
			configure: func(t *testing.T, root string) Options {
				payloadDir := filepath.Join(root, "payload")
				writeTextFile(t, filepath.Join(payloadDir, "payload.go"), `package payload

type Payload struct {
	Name string `+"`json:\"name\"`"+`
}
`)
				return Options{
					PackageName: "models",
					Config: &Config{
						Tables: []TableConfig{
							{
								Name: "Runs",
								Columns: []ColumnConfig{
									{
										Name:            "metadata",
										JSONType:        "payload.Payload",
										JSONTypeImports: []string{"payload=" + moduleImportPath(t, payloadDir)},
									},
								},
							},
						},
					},
				}
			},
		},
		"success: typed json column wrapper compiles": {
			ddl: `CREATE TABLE Runs (
				id STRING(MAX) NOT NULL,
				metadata JSON,
			) PRIMARY KEY (id)`,
			configure: func(t *testing.T, root string) Options {
				payloadDir := filepath.Join(root, "payload")
				writeTextFile(t, filepath.Join(payloadDir, "payload.go"), `package payload

type Payload struct {
	Name string `+"`json:\"name\"`"+`
}
`)
				return Options{
					PackageName: "models",
					Config: &Config{
						Tables: []TableConfig{
							{
								Name: "Runs",
								Columns: []ColumnConfig{
									{
										Name:            "metadata",
										JSONType:        "payload.Payload",
										JSONTypeImports: []string{"payload=" + moduleImportPath(t, payloadDir)},
									},
								},
							},
						},
					},
				}
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			root := newCompileFixtureRoot(t)
			opts := Options{PackageName: "models"}
			if tt.configure != nil {
				opts = tt.configure(t, root)
			}
			outDir := generateFromDDL(t, root, tt.ddl, opts)
			runGoTestDir(t, outDir)
		})
	}
}

func TestGenerator_Generate_TemplatePathOverride(t *testing.T) {
	outDir := filepath.Join(t.TempDir(), "models")
	templateDir := filepath.Join(t.TempDir(), "templates")

	files := map[string]string{
		"header.go.tmpl": `package {{ .PackageName }}

const HeaderOverrideMarker = "header override"
`,
		"spanner_db.go.tmpl": `package {{ .PackageName }}

type SpannerDB interface{}

var SpannerLog = func(...any) {}

const SpannerDBOverrideMarker = "spanner override"
`,
		"type.go.tmpl": `package {{ .PackageName }}

type {{ .Type.Name }} struct{}

func Find{{ .Type.Name }}ByPrimaryKey(db SpannerDB) string {
	_ = db
	return "{{ .Type.Table }}"
}
`,
	}

	for name, content := range files {
		writeTextFile(t, filepath.Join(templateDir, name), content)
	}

	if err := NewGenerator(Options{
		OutDir:       outDir,
		PackageName:  "models",
		TemplatePath: templateDir,
	}).Generate(newSimpleSchema("Users")); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	tests := map[string]struct {
		path string
		want string
	}{
		"header": {
			path: filepath.Join(outDir, "spanner_header.spanner.go"),
			want: `HeaderOverrideMarker = "header override"`,
		},
		"helper": {
			path: filepath.Join(outDir, "spanner_db.spanner.go"),
			want: `SpannerDBOverrideMarker = "spanner override"`,
		},
		"type": {
			path: filepath.Join(outDir, "users.spanner.go"),
			want: `return "Users"`,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			content := readTextFile(t, tt.path)
			if !strings.Contains(content, tt.want) {
				t.Fatalf("%s missing %q", tt.path, tt.want)
			}
		})
	}
}

func TestDetectGoModuleConfig(t *testing.T) {
	tests := map[string]struct {
		setup          func(t *testing.T) string
		wantModulePath string
		wantLang       string
	}{
		"success: nearest go.mod is used": {
			setup: func(t *testing.T) string {
				root := t.TempDir()
				writeTextFile(t, filepath.Join(root, "go.mod"), "module example.com/acme/project\n\ngo 1.26\n")
				outDir := filepath.Join(root, "internal", "models")
				if err := os.MkdirAll(outDir, 0o755); err != nil {
					t.Fatalf("creating out dir: %v", err)
				}
				return outDir
			},
			wantModulePath: "example.com/acme/project",
			wantLang:       "go1.26",
		},
		"success: no go.mod returns empty config": {
			setup: func(t *testing.T) string {
				return t.TempDir()
			},
			wantModulePath: "",
			wantLang:       "",
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			outDir := tt.setup(t)
			gotModulePath, gotLang := detectGoModuleConfig(outDir)
			if gotModulePath != tt.wantModulePath || gotLang != tt.wantLang {
				t.Fatalf("detectGoModuleConfig(%q) = (%q, %q), want (%q, %q)", outDir, gotModulePath, gotLang, tt.wantModulePath, tt.wantLang)
			}
		})
	}
}

func newSimpleSchema(tableNames ...string) *Schema {
	types := make([]Type, 0, len(tableNames))
	for _, tableName := range tableNames {
		typ := Type{
			Name:  snakeToCamel(tableName),
			Table: tableName,
			Fields: []Field{
				{
					Name:            "Id",
					ColumnName:      "id",
					GoType:          "int64",
					SpannerType:     "INT64",
					BaseSpannerType: "INT64",
					NotNull:         true,
					IsPrimaryKey:    true,
				},
			},
		}
		refreshTypeMetadata(&typ)
		types = append(types, typ)
	}
	return &Schema{Types: types}
}

func generateFromSchema(t *testing.T, schema *Schema, opts Options) string {
	t.Helper()

	if opts.OutDir == "" {
		opts.OutDir = filepath.Join(t.TempDir(), "models")
	}
	if opts.PackageName == "" {
		opts.PackageName = "models"
	}

	if err := NewGenerator(opts).Generate(schema); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	return opts.OutDir
}

func generateFromDDL(t *testing.T, root, ddl string, opts Options) string {
	t.Helper()

	schemaPath := filepath.Join(root, "schema.sql")
	writeTextFile(t, schemaPath, ddl)

	schema, err := NewDDLFileSource(schemaPath).Load(t.Context())
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	if opts.OutDir == "" {
		opts.OutDir = filepath.Join(root, "models")
	}

	return generateFromSchema(t, schema, opts)
}

func readTextFile(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return string(data)
}

func writeTextFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("creating directory for %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

func listFiles(t *testing.T, dir string) []string {
	t.Helper()

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("reading directory %s: %v", dir, err)
	}

	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	return names
}

func filterFiles(items []string, keep func(string) bool) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		if keep(item) {
			out = append(out, item)
		}
	}
	return out
}

func newCompileFixtureRoot(t *testing.T) string {
	t.Helper()

	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatalf("creating testdata directory: %v", err)
	}
	root, err := os.MkdirTemp("testdata", "generated-")
	if err != nil {
		t.Fatalf("creating compile fixture root: %v", err)
	}
	root, err = filepath.Abs(root)
	if err != nil {
		t.Fatalf("resolving compile fixture root: %v", err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(root)
	})
	return root
}

func moduleImportPath(t *testing.T, absPath string) string {
	t.Helper()

	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getting working directory: %v", err)
	}
	repoRoot := filepath.Dir(wd)

	rel, err := filepath.Rel(repoRoot, absPath)
	if err != nil {
		t.Fatalf("computing relative path for %s: %v", absPath, err)
	}
	return path.Join("github.com/zchee/spanner-manager", filepath.ToSlash(rel))
}

func runGoTestDir(t *testing.T, dir string) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "go", "test", ".")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go test . in %s failed: %v\n%s", dir, err, output)
	}
}
