// Copyright 2026 The spanner-manager Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codegen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerator_Generate(t *testing.T) {
	outDir := filepath.Join(t.TempDir(), "models")

	schema := &Schema{
		Types: []Type{
			{
				Name:  "Users",
				Table: "Users",
				Fields: []Field{
					{Name: "UserId", ColumnName: "UserId", GoType: "int64", SpannerType: "INT64", NotNull: true, IsPrimaryKey: true},
					{Name: "Name", ColumnName: "Name", GoType: "string", SpannerType: "STRING(MAX)", NotNull: true},
				},
				PrimaryKeyFields: []Field{
					{Name: "UserId", ColumnName: "UserId", GoType: "int64", SpannerType: "INT64", NotNull: true, IsPrimaryKey: true},
				},
			},
		},
	}

	gen := NewGenerator(Options{
		OutDir:      outDir,
		PackageName: "models",
		Language:    "go",
		Suffix:      ".yo.go",
	})

	if err := gen.Generate(schema); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	// Check that files were created.
	expectedFiles := []string{
		"yo_header.yo.go",
		"spanner_db.yo.go",
		"users.yo.go",
	}

	for _, f := range expectedFiles {
		path := filepath.Join(outDir, f)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("expected file %s not found: %v", f, err)
			continue
		}

		content := string(data)

		// Verify it's valid Go (starts with package declaration).
		if !strings.Contains(content, "package models") {
			t.Errorf("file %s does not contain 'package models'", f)
		}

		// Verify generated code marker.
		if !strings.Contains(content, "Code generated by spanner-manager") {
			t.Errorf("file %s does not contain generation marker", f)
		}
	}

	helperFile := filepath.Join(outDir, "spanner_db.yo.go")
	helperData, err := os.ReadFile(helperFile)
	if err != nil {
		t.Fatalf("reading helper file: %v", err)
	}
	helperContent := string(helperData)

	helperChecks := []string{
		"type SpannerDB interface",
		"var SpannerLog",
	}

	for _, check := range helperChecks {
		if !strings.Contains(helperContent, check) {
			t.Errorf("helper file missing %q", check)
		}
	}

	// Verify the type file contains struct definition.
	typeFile := filepath.Join(outDir, "users.yo.go")
	data, err := os.ReadFile(typeFile)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	checks := []string{
		"type Users struct",
		"UserId int64",
		"Name   string",
		"func (t *Users) Insert",
		"func (t *Users) Update",
		"func (t *Users) Delete",
		"func FindUsersByPrimaryKey",
		"db SpannerDB",
	}

	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("type file missing %q", check)
		}
	}
}

func TestGenerator_Generate_IgnoreTables(t *testing.T) {
	outDir := filepath.Join(t.TempDir(), "models")

	schema := &Schema{
		Types: []Type{
			{Name: "Users", Table: "Users", Fields: []Field{{Name: "Id", ColumnName: "Id", GoType: "int64"}}},
			{Name: "Secrets", Table: "Secrets", Fields: []Field{{Name: "Id", ColumnName: "Id", GoType: "int64"}}},
		},
	}

	gen := NewGenerator(Options{
		OutDir:       outDir,
		PackageName:  "models",
		Language:     "go",
		IgnoreTables: []string{"Secrets"},
	})

	if err := gen.Generate(schema); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	// Users file should exist.
	if _, err := os.Stat(filepath.Join(outDir, "users.yo.go")); err != nil {
		t.Errorf("users.yo.go should exist: %v", err)
	}

	// Secrets file should NOT exist.
	if _, err := os.Stat(filepath.Join(outDir, "secrets.yo.go")); err == nil {
		t.Error("secrets.yo.go should not exist (ignored)")
	}
}

func TestGenerator_Generate_CustomConfig(t *testing.T) {
	outDir := filepath.Join(t.TempDir(), "models")

	schema := &Schema{
		Types: []Type{
			{
				Name:  "Users",
				Table: "Users",
				Fields: []Field{
					{Name: "Id", ColumnName: "Id", GoType: "int64", IsPrimaryKey: true},
					{Name: "Data", ColumnName: "Data", GoType: "spanner.NullJSON"},
				},
				PrimaryKeyFields: []Field{
					{Name: "Id", ColumnName: "Id", GoType: "int64", IsPrimaryKey: true},
				},
			},
		},
	}

	gen := NewGenerator(Options{
		OutDir:      outDir,
		PackageName: "models",
		Language:    "go",
		Config: &Config{
			Tables: []TableConfig{
				{
					Name: "Users",
					Columns: []ColumnConfig{
						{Name: "Data", CustomType: "json.RawMessage"},
					},
				},
			},
		},
	})

	if err := gen.Generate(schema); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "users.yo.go"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(string(data), "json.RawMessage") {
		t.Error("expected custom type json.RawMessage in generated code")
	}
}
