// Copyright 2026 The spanner-manager Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Options configures the code generator.
type Options struct {
	OutDir       string
	PackageName  string
	Language     string
	IgnoreTables []string
	Suffix       string
	TemplatePath string
	Config       *Config
}

// Generator orchestrates code generation from a schema.
type Generator struct {
	opts Options
}

// NewGenerator creates a new Generator.
func NewGenerator(opts Options) *Generator {
	if opts.Suffix == "" {
		opts.Suffix = ".yo.go"
	}
	if opts.Language == "" {
		opts.Language = "go"
	}
	if opts.PackageName == "" {
		opts.PackageName = filepath.Base(opts.OutDir)
	}
	return &Generator{opts: opts}
}

// Generate generates code for all types in the schema.
func (g *Generator) Generate(schema *Schema) error {
	if err := os.MkdirAll(g.opts.OutDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	ignoreTables := make(map[string]bool)
	for _, t := range g.opts.IgnoreTables {
		ignoreTables[t] = true
	}

	// Apply custom type mappings from config.
	if g.opts.Config != nil {
		g.applyConfig(schema)
	}

	// Generate header file.
	if err := g.generateHeader(schema); err != nil {
		return fmt.Errorf("generating header: %w", err)
	}

	// Generate yo_db file.
	if err := g.generateYoDB(); err != nil {
		return fmt.Errorf("generating yo_db: %w", err)
	}

	// Generate per-type files.
	for _, t := range schema.Types {
		if ignoreTables[t.Table] {
			continue
		}
		if err := g.generateType(&t); err != nil {
			return fmt.Errorf("generating type %s: %w", t.Name, err)
		}
	}

	return nil
}

func (g *Generator) applyConfig(schema *Schema) {
	if g.opts.Config == nil {
		return
	}

	tableConfigs := make(map[string]*TableConfig)
	for i := range g.opts.Config.Tables {
		tc := &g.opts.Config.Tables[i]
		tableConfigs[tc.Name] = tc
	}

	for i := range schema.Types {
		tc, ok := tableConfigs[schema.Types[i].Table]
		if !ok {
			continue
		}

		colConfigs := make(map[string]string)
		for _, cc := range tc.Columns {
			colConfigs[cc.Name] = cc.CustomType
		}

		for j := range schema.Types[i].Fields {
			if customType, ok := colConfigs[schema.Types[i].Fields[j].ColumnName]; ok {
				schema.Types[i].Fields[j].GoType = customType
			}
		}
	}
}

func (g *Generator) generateHeader(schema *Schema) error {
	tmpl := `// Code generated by spanner-manager; DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"
	"fmt"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
)

// Ensure imports are used.
var _ = context.Background
var _ = fmt.Sprintf
var _ = spanner.Key{}
var _ = iterator.Done
`

	return g.writeTemplate("yo_header"+g.opts.Suffix, tmpl, map[string]any{
		"PackageName": g.opts.PackageName,
		"Types":       schema.Types,
	})
}

func (g *Generator) generateYoDB() error {
	tmpl := `// Code generated by spanner-manager; DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"

	"cloud.google.com/go/spanner"
)

// YODB is the common interface for spanner operations.
type YODB interface {
	ReadRow(ctx context.Context, table string, key spanner.Key, columns []string) (*spanner.Row, error)
	Query(ctx context.Context, statement spanner.Statement) *spanner.RowIterator
}

// YOLog provides an optional logger for generated code.
var YOLog = func(context.Context, string, ...any) {}
`

	return g.writeTemplate("yo_db"+g.opts.Suffix, tmpl, map[string]any{
		"PackageName": g.opts.PackageName,
	})
}

func (g *Generator) generateType(t *Type) error {
	tmpl := `// Code generated by spanner-manager; DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"
	"fmt"

	"cloud.google.com/go/spanner"
)

// {{ .Type.Name }} represents a row from '{{ .Type.Table }}'.
type {{ .Type.Name }} struct {
{{- range .Type.Fields }}
	{{ .Name }} {{ .GoType }} ` + "`" + `spanner:"{{ .ColumnName }}"` + "`" + `
{{- end }}
}

// {{ .Type.Name }}Columns returns the columns for {{ .Type.Name }}.
func {{ .Type.Name }}Columns() []string {
	return []string{
{{- range .Type.Fields }}
		"{{ .ColumnName }}",
{{- end }}
	}
}

// {{ .Type.Name }}PrimaryKeys returns the primary key columns.
func {{ .Type.Name }}PrimaryKeys() []string {
	return []string{
{{- range .Type.PrimaryKeyFields }}
		"{{ .ColumnName }}",
{{- end }}
	}
}

// Insert returns a Mutation to insert a row into {{ .Type.Table }}.
func (t *{{ .Type.Name }}) Insert(ctx context.Context) *spanner.Mutation {
	return spanner.Insert("{{ .Type.Table }}", {{ .Type.Name }}Columns(), []any{
{{- range .Type.Fields }}
		t.{{ .Name }},
{{- end }}
	})
}

// Update returns a Mutation to update a row in {{ .Type.Table }}.
func (t *{{ .Type.Name }}) Update(ctx context.Context) *spanner.Mutation {
	return spanner.Update("{{ .Type.Table }}", {{ .Type.Name }}Columns(), []any{
{{- range .Type.Fields }}
		t.{{ .Name }},
{{- end }}
	})
}

// InsertOrUpdate returns a Mutation to insert or update a row in {{ .Type.Table }}.
func (t *{{ .Type.Name }}) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	return spanner.InsertOrUpdate("{{ .Type.Table }}", {{ .Type.Name }}Columns(), []any{
{{- range .Type.Fields }}
		t.{{ .Name }},
{{- end }}
	})
}

// Delete returns a Mutation to delete the {{ .Type.Name }} row.
func (t *{{ .Type.Name }}) Delete(ctx context.Context) *spanner.Mutation {
	return spanner.Delete("{{ .Type.Table }}", spanner.Key{
{{- range .Type.PrimaryKeyFields }}
		t.{{ .Name }},
{{- end }}
	})
}

// Find{{ .Type.Name }}ByPrimaryKey finds a {{ .Type.Name }} by its primary key.
func Find{{ .Type.Name }}ByPrimaryKey(ctx context.Context, db YODB{{ range .Type.PrimaryKeyFields }}, {{ .Name | lowerFirst }} {{ .GoType }}{{ end }}) (*{{ .Type.Name }}, error) {
	key := spanner.Key{
{{- range .Type.PrimaryKeyFields }}
		{{ .Name | lowerFirst }},
{{- end }}
	}

	row, err := db.ReadRow(ctx, "{{ .Type.Table }}", key, {{ .Type.Name }}Columns())
	if err != nil {
		return nil, fmt.Errorf("finding {{ .Type.Name }}: %w", err)
	}

	var t {{ .Type.Name }}
	if err := row.ToStruct(&t); err != nil {
		return nil, fmt.Errorf("scanning {{ .Type.Name }}: %w", err)
	}

	return &t, nil
}
`

	return g.writeTemplate(strings.ToLower(t.Name)+g.opts.Suffix, tmpl, map[string]any{
		"PackageName": g.opts.PackageName,
		"Type":        t,
	})
}

func (g *Generator) writeTemplate(filename, tmplText string, data any) error {
	funcMap := template.FuncMap{
		"lowerFirst": func(s string) string {
			if s == "" {
				return s
			}
			return strings.ToLower(s[:1]) + s[1:]
		},
	}

	tmpl, err := template.New(filename).Funcs(funcMap).Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Format Go code.
	if g.opts.Language == "go" {
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			// Write unformatted on format error for debugging.
			formatted = buf.Bytes()
		}
		buf.Reset()
		buf.Write(formatted)
	}

	path := filepath.Join(g.opts.OutDir, filename)
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing file %s: %w", path, err)
	}

	return nil
}
